package systemSR;

public enum SRCmdCodes {
	FILL,HIGH_LEVEL_REACHED,EMPTY,LOW_LEVEL_REACHED,
	HEAT,HEATING_COMPLETED,
	MIX,MIXING_COMPLETED, 
	PIPE_RESERVE,PIPE_FREE,
	TRANSFER,TRANSFER_COMPLETED,
	POWER_RESERVE,POWER_FREE;
}
